/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.ConexionSql;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date; 

/**
 *
 * @author Lab10
 */
public class jfEstudiantes extends javax.swing.JFrame {

    /**
     * Creates new form jfEstudiantes
     */
    public jfEstudiantes(){
        initComponents();
        this.cbFacultad.removeAllItems();
        this.cbDepartamento.removeAllItems();
        this.setLocationRelativeTo(null);
        try {
            Connection conex = ConexionSql.getInstancia().getConexion();
            CallableStatement sqlFacultades = conex.prepareCall("select * from Facultades");
            CallableStatement sqlDepartament = conex.prepareCall("select * from DEPSV");
            ResultSet rs1 = sqlFacultades.executeQuery();
            ResultSet rs2 = sqlDepartament.executeQuery();
            while(rs1.next()){
                this.cbFacultad.addItem(rs1.getString("nombreFacultad"));
            }
            while(rs2.next()){
                this.cbDepartamento.addItem(rs2.getString("DepName"));
            }

        } catch (Exception ex) {
            Logger.getLogger(jfEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarCarnet = new javax.swing.JButton();
        tfIdEstudiante = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfCarnet = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfDireccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfTelCasa = new javax.swing.JTextField();
        tfTelOficina = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfTelCelular = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        chkEstado = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        tfDui = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfNit = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnbuscarNombre = new javax.swing.JButton();
        btnbuscarApellido = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        cbCarrera = new javax.swing.JComboBox<>();
        cbDepartamento = new javax.swing.JComboBox<>();
        cbMunicipio = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        cbFacultad = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 204, 0));
        jLabel1.setText("Mantenimiento de estudiantes");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("IdEstudiante:");

        btnBuscarCarnet.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBuscarCarnet.setText("Buscar Carnet");
        btnBuscarCarnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCarnetActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Carnet:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Nombres: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Apellidos:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Direccion:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Tel. Casa:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Tel. Oficina:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Tel. Celular:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Email:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Estado:");

        chkEstado.setText("Activo");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("DUI:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("NIT:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Carrera:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Dep:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Municipio:");

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnbuscarNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnbuscarNombre.setText("Buscar Nombre");
        btnbuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarNombreActionPerformed(evt);
            }
        });

        btnbuscarApellido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnbuscarApellido.setText("Buscar Apellido");
        btnbuscarApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarApellidoActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnCerrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        cbCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCarreraActionPerformed(evt);
            }
        });

        cbDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDepartamentoActionPerformed(evt);
            }
        });

        cbMunicipio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Listado Estudiantes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Facultad:");

        cbFacultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFacultadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(tfIdEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel3)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(tfCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(tfNombre)
                                                    .addComponent(tfApellido)
                                                    .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel14)
                                                                .addComponent(jLabel15))
                                                            .addGap(14, 14, 14))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                            .addComponent(jLabel16)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel17)
                                                        .addGap(9, 9, 9)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(cbCarrera, 0, 559, Short.MAX_VALUE)
                                                    .addComponent(cbDepartamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(cbFacultad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(cbMunicipio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tfDui, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfNit, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(tfTelCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel8)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(tfTelOficina, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel9)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(tfTelCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel11)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(chkEstado))))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(btnBuscarCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnbuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)
                                        .addComponent(btnbuscarApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(303, 303, 303)
                                        .addComponent(jLabel1))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(427, 427, 427)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfIdEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(cbFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(cbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(cbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(cbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfTelCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(tfTelOficina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tfTelCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(chkEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfDui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(tfNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar)
                    .addComponent(btnModificar)
                    .addComponent(btnAgregar)
                    .addComponent(btnbuscarApellido)
                    .addComponent(btnBuscarCarnet)
                    .addComponent(btnbuscarNombre))
                .addGap(16, 16, 16)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnbuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarNombreActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection conex = ConexionSql.getInstancia().getConexion();
            CallableStatement sql = conex.prepareCall("{call SP_ConsultarEstudiante(?,?,?)}");
            String nombre = tfNombre.getText();
            sql.setString(1, "");
            sql.setString(2, nombre);
            sql.setString(3, "");
            ResultSet rs = sql.executeQuery();
            if (rs.next()){ //Valida si la consulta se ejecutó con éxito
                if (rs.getInt(1) > 0){//Valida si existen los datos buscados
                    tfIdEstudiante.setText(String.valueOf(rs.getInt("IdEstudiante")));
                    tfCarnet.setText(rs.getString("Carnet"));
                    tfNombre.setText(rs.getString("Nombres"));
                    tfApellido.setText(rs.getString("Apellidos"));
                    tfDireccion.setText(rs.getString("Direccion"));
                    tfTelCasa.setText(rs.getString("TelefonoCasa"));
                    tfTelOficina.setText(rs.getString("TelefonoTrabajo"));
                    tfTelCelular.setText(rs.getString("TelefonoCelular"));
                    tfEmail.setText(rs.getString("Email"));
                    chkEstado.setSelected(rs.getBoolean("Estado"));
                    tfDui.setText(rs.getString("Dui"));
                    tfNit.setText(rs.getString("Nit"));
                    cbFacultad.setSelectedIndex(rs.getInt("IdFacultad")-1);
                    cbCarrera.setSelectedIndex(rs.getInt("IdCarrera")-1);
                    cbDepartamento.setSelectedIndex(rs.getInt("IdDep")-1);
                    cbMunicipio.setSelectedIndex(rs.getInt("IdMunicipio")-1);
                    
                }
                else{
                    JOptionPane.showMessageDialog(null, "El usuario no existe");
                }   
            }
            else{
                JOptionPane.showMessageDialog(null, "La consulta no se pudo ejecutar");
            }
        } catch (Exception ex) {
            Logger.getLogger(jfEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnbuscarNombreActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        jfMenu menu = new jfMenu();
        menu.setVisible(true);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnBuscarCarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCarnetActionPerformed
        try {
            // TODO add your handling code here:
            Connection conex = ConexionSql.getInstancia().getConexion();
            CallableStatement sql = conex.prepareCall("{call SP_ConsultarEstudiante(?,?,?)}");
            String carnet = tfCarnet.getText();
            sql.setString(1, carnet);
            sql.setString(2, "");
            sql.setString(3, "");
            ResultSet rs = sql.executeQuery();
            if (rs.next()){ //Valida si la consulta se ejecutó con éxito
                if (rs.getInt(1) > 0){//Valida si existen los datos buscados
                    tfIdEstudiante.setText(String.valueOf(rs.getInt("IdEstudiante")));
                    tfCarnet.setText(rs.getString("Carnet"));
                    tfNombre.setText(rs.getString("Nombres"));
                    tfApellido.setText(rs.getString("Apellidos"));
                    tfDireccion.setText(rs.getString("Direccion"));
                    tfTelCasa.setText(rs.getString("TelefonoCasa"));
                    tfTelOficina.setText(rs.getString("TelefonoTrabajo"));
                    tfTelCelular.setText(rs.getString("TelefonoCelular"));
                    tfEmail.setText(rs.getString("Email"));
                    chkEstado.setSelected(rs.getBoolean("Estado"));
                    tfDui.setText(rs.getString("Dui"));
                    tfNit.setText(rs.getString("Nit"));
                    cbFacultad.setSelectedIndex(rs.getInt("IdFacultad")-1);
                    cbCarrera.setSelectedIndex(rs.getInt("IdCarrera")-1);
                    cbDepartamento.setSelectedIndex(rs.getInt("IdDep")-1);
                    cbMunicipio.setSelectedIndex(rs.getInt("IdMunicipio")-1);
                    
                }
                else{
                    JOptionPane.showMessageDialog(null, "El usuario no existe");
                }   
            }
            else{
                JOptionPane.showMessageDialog(null, "La consulta no se pudo ejecutar");
            }
        } catch (Exception ex) {
            Logger.getLogger(jfEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarCarnetActionPerformed

    private void btnbuscarApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarApellidoActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection conex = ConexionSql.getInstancia().getConexion();
            CallableStatement sql = conex.prepareCall("{call SP_ConsultarEstudiante(?,?,?)}");
            String apellido = tfApellido.getText();
            sql.setString(1, "");
            sql.setString(2, "");
            sql.setString(3, apellido);
            ResultSet rs = sql.executeQuery();
            if (rs.next()){ //Valida si la consulta se ejecutó con éxito
                if (rs.getInt(1) > 0){//Valida si existen los datos buscados
                    tfIdEstudiante.setText(String.valueOf(rs.getInt("IdEstudiante")));
                    tfCarnet.setText(rs.getString("Carnet"));
                    tfNombre.setText(rs.getString("Nombres"));
                    tfApellido.setText(rs.getString("Apellidos"));
                    tfDireccion.setText(rs.getString("Direccion"));
                    tfTelCasa.setText(rs.getString("TelefonoCasa"));
                    tfTelOficina.setText(rs.getString("TelefonoTrabajo"));
                    tfTelCelular.setText(rs.getString("TelefonoCelular"));
                    tfEmail.setText(rs.getString("Email"));
                    chkEstado.setSelected(rs.getBoolean("Estado"));
                    tfDui.setText(rs.getString("Dui"));
                    tfNit.setText(rs.getString("Nit"));
                    cbFacultad.setSelectedIndex(rs.getInt("IdFacultad")-1);
                    cbCarrera.setSelectedIndex(rs.getInt("IdCarrera")-1);
                    cbDepartamento.setSelectedIndex(rs.getInt("IdDep")-1);
                    cbMunicipio.setSelectedIndex(rs.getInt("IdMunicipio")-1);
                    
                }
                else{
                    JOptionPane.showMessageDialog(null, "El usuario no existe");
                }   
            }
            else{
                JOptionPane.showMessageDialog(null, "La consulta no se pudo ejecutar");
            }
        } catch (Exception ex) {
            Logger.getLogger(jfEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnbuscarApellidoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        try {
            Connection conex = ConexionSql.getInstancia().getConexion();
            CallableStatement sql = conex.prepareCall("{call SP_ModificarEstudiante(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)}");
            sql.setInt(1, Integer.parseInt(tfIdEstudiante.getText()));
            sql.setString(2, tfCarnet.getText());
            sql.setString(3, tfNombre.getText());
            sql.setString(4, tfApellido.getText());
            sql.setString(5, tfDireccion.getText());
            sql.setString(6, tfTelCasa.getText());
            sql.setString(7, tfTelOficina.getText());
            sql.setString(8, tfTelCelular.getText());
            sql.setString(9, tfEmail.getText());
            sql.setBoolean(10,chkEstado.isSelected());
            sql.setString(11, tfDui.getText());
            sql.setString(12, tfNit.getText());
            sql.setInt(13, cbCarrera.getSelectedIndex()+1);
            sql.setInt(14, cbMunicipio.getSelectedIndex()+1);
            sql.setInt(15, cbDepartamento.getSelectedIndex()+1);
            sql.setInt(16, cbFacultad.getSelectedIndex()+1);
            sql.execute();
            JOptionPane.showMessageDialog(null, "Registro modificado!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        try {
            if((tfCarnet.getText().length()!=0) && (tfNombre.getText().length()!=0) && (tfApellido.getText().length()!=0)){
                Connection conex = ConexionSql.getInstancia().getConexion();
                CallableStatement sql = conex.prepareCall("{call SP_AgregarEstudiantes(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)}");
                sql.setString(1, tfCarnet.getText());
                sql.setString(2, tfNombre.getText());
                sql.setString(3, tfApellido.getText());
                sql.setString(4, tfDireccion.getText());
                sql.setString(5, tfTelCasa.getText());
                sql.setString(6, tfTelOficina.getText());
                sql.setString(7, tfTelCelular.getText());
                sql.setString(8, tfEmail.getText());
                sql.setBoolean(9,chkEstado.isSelected());
                sql.setString(10, tfDui.getText());
                sql.setString(11, tfNit.getText());
                sql.setInt(12, cbCarrera.getSelectedIndex()+1);
                sql.setInt(13, cbMunicipio.getSelectedIndex()+1);
                sql.setInt(14, cbDepartamento.getSelectedIndex()+1);
                sql.setInt(15, cbFacultad.getSelectedIndex()+1);
                sql.registerOutParameter(16, java.sql.Types.INTEGER);
                sql.execute();
                tfIdEstudiante.setText(String.valueOf(sql.getInt(16)));
                Date fecha = new Date();
                //JOptionPane.showMessageDialog(null, fecha);
                Calendar c1 = Calendar.getInstance();
                JOptionPane.showMessageDialog(null, "Registro agregado!");
            }else{
                JOptionPane.showMessageDialog(null, "Hay campos vacios!");
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Para establecer el modelo al JTable
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            this.jTable1.setModel(modelo);
            Connection conex = ConexionSql.getInstancia().getConexion();
            CallableStatement sql = conex.prepareCall("{call SP_ListarEstudiantes}");
            ResultSet rs = sql.executeQuery();
            //Obteniendo la informacion de las columnas que estan siendo consultadas
            ResultSetMetaData rsMd = rs.getMetaData();
            //La cantidad de columnas que tiene la consulta
            int cantidadColumnas = rsMd.getColumnCount();
             //Establecer como cabezeras el nombre de las colimnas
            for (int i = 1; i <= cantidadColumnas; i++) {
                modelo.addColumn(rsMd.getColumnLabel(i));
            }
             //Creando las filas para el JTable
            while (rs.next()) {
                Object[] fila = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    fila[i]=rs.getObject(i+1);
                }
                modelo.addRow(fila);
            }
            rs.close();
        } catch (Exception ex) {
            Logger.getLogger(jfEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbFacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFacultadActionPerformed
        // TODO add your handling code here:
        this.cbCarrera.removeAllItems();
        try {
            Connection conex = ConexionSql.getInstancia().getConexion();          
            CallableStatement sql = conex.prepareCall("select NombreCarrera from Carreras where IdFacultad = '"+(this.cbFacultad.getSelectedIndex()+1)+"'");
            ResultSet rs = sql.executeQuery();
            while(rs.next()){
                this.cbCarrera.addItem(rs.getString("NombreCarrera"));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
            
    }//GEN-LAST:event_cbFacultadActionPerformed

    private void cbDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDepartamentoActionPerformed
        // TODO add your handling code here:
        this.cbMunicipio.removeAllItems();
        try {
            Connection conex = ConexionSql.getInstancia().getConexion();
            CallableStatement sql = conex.prepareCall("select MunName from MUNSV where DEPSV_ID = '"+(this.cbDepartamento.getSelectedIndex()+1)+"'");
            ResultSet rs = sql.executeQuery();
            while(rs.next()){
                this.cbMunicipio.addItem(rs.getString("MunName"));
            }
        } catch (Exception ex) {
            Logger.getLogger(jfEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_cbDepartamentoActionPerformed

    private void cbCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCarreraActionPerformed

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfEstudiantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarCarnet;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnbuscarApellido;
    private javax.swing.JButton btnbuscarNombre;
    private javax.swing.JComboBox<String> cbCarrera;
    private javax.swing.JComboBox<String> cbDepartamento;
    private javax.swing.JComboBox cbFacultad;
    private javax.swing.JComboBox<String> cbMunicipio;
    private javax.swing.JCheckBox chkEstado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfCarnet;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfDui;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfIdEstudiante;
    private javax.swing.JTextField tfNit;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfTelCasa;
    private javax.swing.JTextField tfTelCelular;
    private javax.swing.JTextField tfTelOficina;
    // End of variables declaration//GEN-END:variables
}
