/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.ConexionSql;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date; 


/**
 *
 * @author ProgrammerPC
 */
public class jfInscripcionDetalle extends javax.swing.JFrame {

    /**
     * Creates new form jfInscripcionDetalle
     */
    public jfInscripcionDetalle() {
        initComponents();
        tfIdInscripcion.setEditable(false);
        tfCarnet.setEditable(false);
        tfNombre.setEditable(false);
        tfApellido.setEditable(false);
        
        
        
        this.setLocationRelativeTo(null);
        try {
            Connection conex = ConexionSql.getInstancia().getConexion();
            CallableStatement sqlCiclo= conex.prepareCall("select * from Materias order by NombreMateria asc");
            ResultSet rs1 = sqlCiclo.executeQuery();
            this.cbMateria1.addItem(("0,N/A"));
            this.cbMateria2.addItem(("0,N/A"));
            this.cbMateria3.addItem(("0,N/A"));
            this.cbMateria4.addItem(("0,N/A"));
            this.cbMateria5.addItem(("0,N/A"));            
            while(rs1.next()){                
                this.cbMateria1.addItem((rs1.getString("IdMateria"))+",  "+(rs1.getString("NombreMateria")));
                this.cbMateria2.addItem((rs1.getString("IdMateria"))+",  "+(rs1.getString("NombreMateria")));
                this.cbMateria3.addItem((rs1.getString("IdMateria"))+",  "+(rs1.getString("NombreMateria")));
                this.cbMateria4.addItem((rs1.getString("IdMateria"))+",  "+(rs1.getString("NombreMateria")));
                this.cbMateria5.addItem((rs1.getString("IdMateria"))+",  "+(rs1.getString("NombreMateria")));
            }

        } catch (Exception ex) {
            Logger.getLogger(jfInscripcionDetalle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfIdInscripcion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfCarnet = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfApellido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbMateria1 = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        cbMateria2 = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        cbMateria3 = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        cbMateria4 = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        cbMateria5 = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Id Inscripcion");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Carnet:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Nombres: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Apellidos:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 204, 0));
        jLabel1.setText("Inscripcion de Materias");

        cbMateria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMateria1ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Materia 1:");

        cbMateria2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMateria2ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Materia 2:");

        cbMateria3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMateria3ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Materia 3:");

        cbMateria4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMateria4ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Materia 4:");

        cbMateria5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMateria5ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Materia 5:");

        btnCerrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAgregar.setText("Guardar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(jLabel17)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbMateria5, 0, 240, Short.MAX_VALUE)
                    .addComponent(cbMateria4, 0, 240, Short.MAX_VALUE)
                    .addComponent(cbMateria3, 0, 240, Short.MAX_VALUE)
                    .addComponent(cbMateria2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbMateria1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfCarnet, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(tfIdInscripcion))
                        .addComponent(tfApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                        .addComponent(tfNombre)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIdInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(cbMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(cbMateria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(cbMateria3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(cbMateria4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(cbMateria5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar)
                    .addComponent(btnAgregar))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMateria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMateria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMateria1ActionPerformed

    private void cbMateria2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMateria2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMateria2ActionPerformed

    private void cbMateria3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMateria3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMateria3ActionPerformed

    private void cbMateria4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMateria4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMateria4ActionPerformed

    private void cbMateria5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMateria5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMateria5ActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        jfMenu menu = new jfMenu();
        menu.setVisible(true);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void insertarnotas(int id){
        try {
            Connection conex = ConexionSql.getInstancia().getConexion();
            
            CallableStatement sql = conex.prepareCall("{call [SP_AgregarDetalleNotas](?)}");
            sql.setInt(1, id);
            sql.execute();
         
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        try {
            if((tfIdInscripcion.getText().length()!=0)){
                
                Connection conex = ConexionSql.getInstancia().getConexion();
                
                String materia1 = (String) cbMateria1.getSelectedItem();
                String[] parts1 = materia1.split(",");
                String partmateria1 = parts1[0]; // 123
                
                String materia2 = (String) cbMateria2.getSelectedItem();
                String[] parts2 = materia2.split(",");
                String partmateria2 = parts2[0]; // 123
                
                String materia3 = (String) cbMateria3.getSelectedItem();
                String[] parts3 = materia3.split(",");
                String partmateria3 = parts3[0]; // 123
                
                String materia4 = (String) cbMateria4.getSelectedItem();
                String[] parts4 = materia4.split(",");
                String partmateria4 = parts4[0]; // 123
                
                String materia5 = (String) cbMateria5.getSelectedItem();
                String[] parts5 = materia5.split(",");
                String partmateria5 = parts5[0]; // 123
                
                if(Integer.parseInt(partmateria1)>0){
                    CallableStatement sql = conex.prepareCall("{call SP_AgregarDetalleInscripcion(?,?,?)}");
                    sql.setInt(1, Integer.parseInt(tfIdInscripcion.getText()));
                    sql.setInt(2, Integer.parseInt(partmateria1));
                    sql.registerOutParameter(3, java.sql.Types.INTEGER);
                    sql.execute();
                    insertarnotas(sql.getInt(3));                    
                } 
                if(Integer.parseInt(partmateria2)>0){
                    CallableStatement sql = conex.prepareCall("{call SP_AgregarDetalleInscripcion(?,?,?)}");
                    sql.setInt(1, Integer.parseInt(tfIdInscripcion.getText()));
                    sql.setInt(2, Integer.parseInt(partmateria2));
                    sql.registerOutParameter(3, java.sql.Types.INTEGER);
                    sql.execute();
                    insertarnotas(sql.getInt(3));
                } 
                if(Integer.parseInt(partmateria3)>0){
                    CallableStatement sql = conex.prepareCall("{call SP_AgregarDetalleInscripcion(?,?,?)}");
                    sql.setInt(1, Integer.parseInt(tfIdInscripcion.getText()));
                    sql.setInt(2, Integer.parseInt(partmateria3));
                    sql.registerOutParameter(3, java.sql.Types.INTEGER);                
                    sql.execute();                    
                    insertarnotas(sql.getInt(3));    
                } 
                if(Integer.parseInt(partmateria4)>0){
                    CallableStatement sql = conex.prepareCall("{call SP_AgregarDetalleInscripcion(?,?,?)}");
                    sql.setInt(1, Integer.parseInt(tfIdInscripcion.getText()));
                    sql.setInt(2, Integer.parseInt(partmateria4));
                    sql.registerOutParameter(3, java.sql.Types.INTEGER);                    
                    sql.execute();
                    insertarnotas(sql.getInt(3));
                } 
                if(Integer.parseInt(partmateria5)>0){
                    CallableStatement sql = conex.prepareCall("{call SP_AgregarDetalleInscripcion(?,?,?)}");
                    sql.setInt(1, Integer.parseInt(tfIdInscripcion.getText()));
                    sql.setInt(2, Integer.parseInt(partmateria5));
                    sql.registerOutParameter(3, java.sql.Types.INTEGER);
                    sql.execute();
                    insertarnotas(sql.getInt(3));
                } 
                
                JOptionPane.showMessageDialog(null, "Inscripcion Exitosa!");
                this.dispose();
                jfMenu menu = new jfMenu();
                menu.setVisible(true);

            }else{
                JOptionPane.showMessageDialog(null, "Hay campos vacios!");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfInscripcionDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfInscripcionDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfInscripcionDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfInscripcionDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfInscripcionDetalle().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnCerrar;
    private javax.swing.JComboBox cbMateria1;
    private javax.swing.JComboBox cbMateria2;
    private javax.swing.JComboBox cbMateria3;
    private javax.swing.JComboBox cbMateria4;
    private javax.swing.JComboBox cbMateria5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JTextField tfApellido;
    public javax.swing.JTextField tfCarnet;
    public javax.swing.JTextField tfIdInscripcion;
    public javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
