/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.ConexionSql;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date; 

/**
 *
 * @author ProgrammerPC
 */
public class jfMantemientoInscripciones extends javax.swing.JFrame {

    /**
     * Creates new form jfMantemientoInscripciones
     */
    public jfMantemientoInscripciones() {
        initComponents();
        tfIdInscripcion.setEditable(false);
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbMateria4 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        cbMateria5 = new javax.swing.JComboBox();
        tfApellido = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        cbMateria1 = new javax.swing.JComboBox();
        btnAgregar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        cbMateria2 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbMateria3 = new javax.swing.JComboBox();
        tfCarnet = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfIdInscripcion = new javax.swing.JTextField();
        btnBuscarCarnet = new javax.swing.JButton();
        btnbuscarNombre = new javax.swing.JButton();
        btnbuscarApellido = new javax.swing.JButton();
        btnAgregar1 = new javax.swing.JButton();
        btnAgregar2 = new javax.swing.JButton();
        btnAgregar3 = new javax.swing.JButton();
        btnAgregar4 = new javax.swing.JButton();
        btnAgregar5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbMateria4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMateria4ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Apellidos:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Materia 4:");

        cbMateria5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMateria5ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Materia 5:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 204, 0));
        jLabel1.setText("Retiro de Materias o de Ciclo");

        btnCerrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        cbMateria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMateria1ActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAgregar.setText("Retirar Ciclo Completo");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Materia 1:");

        cbMateria2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMateria2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Id Inscripcion");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Materia 2:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Carnet:");

        cbMateria3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMateria3ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Materia 3:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Nombres: ");

        btnBuscarCarnet.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBuscarCarnet.setText("Buscar Carnet");
        btnBuscarCarnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCarnetActionPerformed(evt);
            }
        });

        btnbuscarNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnbuscarNombre.setText("Buscar Nombre");
        btnbuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarNombreActionPerformed(evt);
            }
        });

        btnbuscarApellido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnbuscarApellido.setText("Buscar Apellido");
        btnbuscarApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarApellidoActionPerformed(evt);
            }
        });

        btnAgregar1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAgregar1.setText("Retirar Materia");
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });

        btnAgregar2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAgregar2.setText("Retirar Materia");
        btnAgregar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar2ActionPerformed(evt);
            }
        });

        btnAgregar3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAgregar3.setText("Retirar Materia");
        btnAgregar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar3ActionPerformed(evt);
            }
        });

        btnAgregar4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAgregar4.setText("Retirar Materia");
        btnAgregar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar4ActionPerformed(evt);
            }
        });

        btnAgregar5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAgregar5.setText("Retirar Materia");
        btnAgregar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel17)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbMateria4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbMateria3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbMateria2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbMateria1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfCarnet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(tfIdInscripcion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(tfNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbMateria5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnbuscarApellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                .addComponent(btnAgregar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgregar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgregar4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgregar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgregar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnBuscarCarnet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnbuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 246, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfIdInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscarCarnet)
                        .addGap(5, 5, 5)
                        .addComponent(btnbuscarNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbuscarApellido)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAgregar1)))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbMateria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAgregar2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbMateria3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAgregar3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbMateria4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAgregar4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbMateria5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAgregar5)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar)
                    .addComponent(btnAgregar))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMateria4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMateria4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMateria4ActionPerformed

    private void cbMateria5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMateria5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMateria5ActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        jfMenu menu = new jfMenu();
        menu.setVisible(true);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void cbMateria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMateria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMateria1ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        try {
            Connection conex = ConexionSql.getInstancia().getConexion();
            CallableStatement sql = conex.prepareCall("{call SP_RetirarCiclo(?)}");
            sql.setInt(1, Integer.parseInt(tfIdInscripcion.getText()));
            sql.execute();
            JOptionPane.showMessageDialog(null, "Ciclo retirado con exito!");
            
            this.dispose();
            jfMenu menu = new jfMenu();
            menu.setVisible(true);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void cbMateria2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMateria2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMateria2ActionPerformed

    private void cbMateria3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMateria3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMateria3ActionPerformed
    int i;
    private void llenarmaterias(int id){
        try {
            
            Connection conex = ConexionSql.getInstancia().getConexion();
            
            CallableStatement sqlMaterias= conex.prepareCall("select * from Materias");
            ResultSet rs1 = sqlMaterias.executeQuery();
            this.cbMateria1.removeAllItems();
            this.cbMateria2.removeAllItems();
            this.cbMateria3.removeAllItems();
            this.cbMateria4.removeAllItems();
            this.cbMateria5.removeAllItems();            
            
            this.cbMateria1.addItem(("0,N/A"));
            this.cbMateria2.addItem(("0,N/A"));
            this.cbMateria3.addItem(("0,N/A"));
            this.cbMateria4.addItem(("0,N/A"));
            this.cbMateria5.addItem(("0,N/A"));            
            while(rs1.next()){                
                this.cbMateria1.addItem((rs1.getString("IdMateria"))+",  "+(rs1.getString("NombreMateria")));
                this.cbMateria2.addItem((rs1.getString("IdMateria"))+",  "+(rs1.getString("NombreMateria")));
                this.cbMateria3.addItem((rs1.getString("IdMateria"))+",  "+(rs1.getString("NombreMateria")));
                this.cbMateria4.addItem((rs1.getString("IdMateria"))+",  "+(rs1.getString("NombreMateria")));
                this.cbMateria5.addItem((rs1.getString("IdMateria"))+",  "+(rs1.getString("NombreMateria")));
            }
            
            CallableStatement sqlMateriasInscritas= conex.prepareCall("select * from InscripcionesDetalles where estado = 0 and IdInscripcion="+id);
            ResultSet rs2 = sqlMateriasInscritas.executeQuery();   
            i=1;
            while(rs2.next()){                
                if(i==1){
                    cbMateria1.setSelectedIndex(rs2.getInt("IdMateria"));
                }
                if(i==2){
                    cbMateria2.setSelectedIndex(rs2.getInt("IdMateria"));
                }
                if(i==3){
                    cbMateria3.setSelectedIndex(rs2.getInt("IdMateria"));
                }
                if(i==4){
                    cbMateria4.setSelectedIndex(rs2.getInt("IdMateria"));
                }
                if(i==5){
                    cbMateria5.setSelectedIndex(rs2.getInt("IdMateria"));
                }
                i++;
            }

        } catch (Exception ex) {
            Logger.getLogger(jfInscripcionDetalle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    private void btnBuscarCarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCarnetActionPerformed
        try {
            // TODO add your handling code here:
            Connection conex = ConexionSql.getInstancia().getConexion();
            CallableStatement sql = conex.prepareCall("{call [SP_ConsultarEstudianteMatriculados](?,?,?)}");
            String carnet = tfCarnet.getText();
            sql.setString(1, carnet);
            sql.setString(2, "");
            sql.setString(3, "");
            ResultSet rs = sql.executeQuery();
            if (rs.next()){ //Valida si la consulta se ejecutó con éxito
                if (rs.getInt(1) > 0){//Valida si existen los datos buscados
                    tfIdInscripcion.setText(String.valueOf(rs.getInt("IdInscripcion")));
                    tfCarnet.setText(rs.getString("Carnet"));
                    tfNombre.setText(rs.getString("Nombres"));
                    tfApellido.setText(rs.getString("Apellidos"));
                    llenarmaterias(rs.getInt("IdInscripcion"));
                }
                else{
                    JOptionPane.showMessageDialog(null, "El usuario no existe o no tiene ninguna matricula activa");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "La consulta no se pudo ejecutar");
            }
        } catch (Exception ex) {
            Logger.getLogger(jfEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarCarnetActionPerformed

    private void btnbuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarNombreActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection conex = ConexionSql.getInstancia().getConexion();
            CallableStatement sql = conex.prepareCall("{call [SP_ConsultarEstudianteMatriculados](?,?,?)}");
            String nombre = tfNombre.getText();
            sql.setString(1, "");
            sql.setString(2, nombre);
            sql.setString(3, "");
            ResultSet rs = sql.executeQuery();
            if (rs.next()){ //Valida si la consulta se ejecutó con éxito
                if (rs.getInt(1) > 0){//Valida si existen los datos buscados
                    tfIdInscripcion.setText(String.valueOf(rs.getInt("IdInscripcion")));
                    tfCarnet.setText(rs.getString("Carnet"));
                    tfNombre.setText(rs.getString("Nombres"));
                    tfApellido.setText(rs.getString("Apellidos"));
                    llenarmaterias(rs.getInt("IdInscripcion"));
                }
                else{
                    JOptionPane.showMessageDialog(null, "El usuario no existe o no tiene ninguna matricula activa");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "La consulta no se pudo ejecutar");
            }
        } catch (Exception ex) {
            Logger.getLogger(jfEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnbuscarNombreActionPerformed

    private void btnbuscarApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarApellidoActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection conex = ConexionSql.getInstancia().getConexion();
            CallableStatement sql = conex.prepareCall("{call [SP_ConsultarEstudianteMatriculados](?,?,?)}");
            String apellido = tfApellido.getText();
            sql.setString(1, "");
            sql.setString(2, "");
            sql.setString(3, apellido);
            ResultSet rs = sql.executeQuery();
            if (rs.next()){ //Valida si la consulta se ejecutó con éxito
                if (rs.getInt(1) > 0){//Valida si existen los datos buscados
                    tfIdInscripcion.setText(String.valueOf(rs.getInt("IdInscripcion")));
                    tfCarnet.setText(rs.getString("Carnet"));
                    tfNombre.setText(rs.getString("Nombres"));
                    tfApellido.setText(rs.getString("Apellidos"));
                    llenarmaterias(rs.getInt("IdInscripcion"));
                }
                else{
                    JOptionPane.showMessageDialog(null, "El usuario no existe o no tiene ninguna matricula activa");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "La consulta no se pudo ejecutar");
            }
        } catch (Exception ex) {
            Logger.getLogger(jfEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnbuscarApellidoActionPerformed

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
        // TODO add your handling code here:
        try {
            Connection conex = ConexionSql.getInstancia().getConexion();
            CallableStatement sql = conex.prepareCall("{call SP_RetirarMateria(?,?)}");
            sql.setInt(1, Integer.parseInt(tfIdInscripcion.getText()));
            sql.setInt(2, cbMateria1.getSelectedIndex());
            sql.execute();
            JOptionPane.showMessageDialog(null, "Materia retirada con exito!");
            llenarmaterias(Integer.parseInt(tfIdInscripcion.getText()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnAgregar1ActionPerformed

    private void btnAgregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar2ActionPerformed
        // TODO add your handling code here:
        try {
            Connection conex = ConexionSql.getInstancia().getConexion();
            CallableStatement sql = conex.prepareCall("{call SP_RetirarMateria(?,?)}");
            sql.setInt(1, Integer.parseInt(tfIdInscripcion.getText()));
            sql.setInt(2, cbMateria2.getSelectedIndex());
            sql.execute();
            JOptionPane.showMessageDialog(null, "Materia retirada con exito!");
            llenarmaterias(Integer.parseInt(tfIdInscripcion.getText()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnAgregar2ActionPerformed

    private void btnAgregar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar3ActionPerformed
        // TODO add your handling code here:
        try {
            Connection conex = ConexionSql.getInstancia().getConexion();
            CallableStatement sql = conex.prepareCall("{call SP_RetirarMateria(?,?)}");
            sql.setInt(1, Integer.parseInt(tfIdInscripcion.getText()));
            sql.setInt(2, cbMateria3.getSelectedIndex());
            sql.execute();
            JOptionPane.showMessageDialog(null, "Materia retirada con exito!");
            llenarmaterias(Integer.parseInt(tfIdInscripcion.getText()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnAgregar3ActionPerformed

    private void btnAgregar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar4ActionPerformed
        // TODO add your handling code here:
        try {
            Connection conex = ConexionSql.getInstancia().getConexion();
            CallableStatement sql = conex.prepareCall("{call SP_RetirarMateria(?,?)}");
            sql.setInt(1, Integer.parseInt(tfIdInscripcion.getText()));
            sql.setInt(2, cbMateria4.getSelectedIndex());
            sql.execute();
            JOptionPane.showMessageDialog(null, "Materia retirada con exito!");
            llenarmaterias(Integer.parseInt(tfIdInscripcion.getText()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }//GEN-LAST:event_btnAgregar4ActionPerformed

    private void btnAgregar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar5ActionPerformed
        // TODO add your handling code here:
        try {
            Connection conex = ConexionSql.getInstancia().getConexion();
            CallableStatement sql = conex.prepareCall("{call SP_RetirarMateria(?,?)}");
            sql.setInt(1, Integer.parseInt(tfIdInscripcion.getText()));
            sql.setInt(2, cbMateria5.getSelectedIndex());
            sql.execute();
            JOptionPane.showMessageDialog(null, "Materia retirada con exito!");
            llenarmaterias(Integer.parseInt(tfIdInscripcion.getText()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnAgregar5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfMantemientoInscripciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfMantemientoInscripciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfMantemientoInscripciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfMantemientoInscripciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfMantemientoInscripciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnAgregar2;
    private javax.swing.JButton btnAgregar3;
    private javax.swing.JButton btnAgregar4;
    private javax.swing.JButton btnAgregar5;
    private javax.swing.JButton btnBuscarCarnet;
    public javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnbuscarApellido;
    private javax.swing.JButton btnbuscarNombre;
    private javax.swing.JComboBox cbMateria1;
    private javax.swing.JComboBox cbMateria2;
    private javax.swing.JComboBox cbMateria3;
    private javax.swing.JComboBox cbMateria4;
    private javax.swing.JComboBox cbMateria5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JTextField tfApellido;
    public javax.swing.JTextField tfCarnet;
    public javax.swing.JTextField tfIdInscripcion;
    public javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
