/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author Lab10
 */
public class jfMenu extends javax.swing.JFrame {

    /**
     * Creates new form jfMenu
     */
    public jfMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jmMtto = new javax.swing.JMenu();
        jmMttoiUsuarios = new javax.swing.JMenuItem();
        jmMttoEstudiantes = new javax.swing.JMenuItem();
        jmMttoInscripciones = new javax.swing.JMenuItem();
        jmMttomantenimientoInscripciones = new javax.swing.JMenuItem();
        jmMttoNotas = new javax.swing.JMenuItem();
        jmConsultas = new javax.swing.JMenu();
        jmiListar = new javax.swing.JMenuItem();
        jmReportes = new javax.swing.JMenu();
        jmiReporteUsuarios = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmMtto.setText("Mantenimientos");

        jmMttoiUsuarios.setText("Usuarios");
        jmMttoiUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMttoiUsuariosActionPerformed(evt);
            }
        });
        jmMtto.add(jmMttoiUsuarios);

        jmMttoEstudiantes.setText("Estudiantes");
        jmMttoEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMttoEstudiantesActionPerformed(evt);
            }
        });
        jmMtto.add(jmMttoEstudiantes);

        jmMttoInscripciones.setLabel("Inscripciones");
        jmMttoInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMttoInscripcionesActionPerformed(evt);
            }
        });
        jmMtto.add(jmMttoInscripciones);
        jmMttoInscripciones.getAccessibleContext().setAccessibleDescription("");

        jmMttomantenimientoInscripciones.setText("Retiro de Ciclo y Materias");
        jmMttomantenimientoInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMttomantenimientoInscripcionesActionPerformed(evt);
            }
        });
        jmMtto.add(jmMttomantenimientoInscripciones);

        jmMttoNotas.setText("Notas");
        jmMttoNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMttoNotasActionPerformed(evt);
            }
        });
        jmMtto.add(jmMttoNotas);

        jMenuBar1.add(jmMtto);

        jmConsultas.setText("Consultas");

        jmiListar.setText("Listar Usuarios");
        jmConsultas.add(jmiListar);

        jMenuBar1.add(jmConsultas);

        jmReportes.setText("Reportes");

        jmiReporteUsuarios.setText("Usuarios");
        jmReportes.add(jmiReporteUsuarios);

        jMenuBar1.add(jmReportes);

        jmSalir.setText("Salir");
        jmSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmMttoiUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMttoiUsuariosActionPerformed
        // TODO add your handling code here:
        this.dispose();
        jfUsuarios usuarios = new jfUsuarios();
        usuarios.setVisible(true);        
    }//GEN-LAST:event_jmMttoiUsuariosActionPerformed

    private void jmSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSalirMouseClicked
        // TODO add your handling code here:
        this.dispose();
        jfLogin login = new jfLogin();
        login.setVisible(true);
    }//GEN-LAST:event_jmSalirMouseClicked

    private void jmMttoEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMttoEstudiantesActionPerformed
        // TODO add your handling code here:
        this.dispose();
        jfEstudiantes estudiantes = new jfEstudiantes();
        estudiantes.setVisible(true);  
    }//GEN-LAST:event_jmMttoEstudiantesActionPerformed

    private void jmMttoInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMttoInscripcionesActionPerformed
        // TODO add your handling code here:
        this.dispose();
        jfInscripciones inscripciones = new jfInscripciones();
        inscripciones.setVisible(true); 
    }//GEN-LAST:event_jmMttoInscripcionesActionPerformed

    private void jmMttomantenimientoInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMttomantenimientoInscripcionesActionPerformed
        // TODO add your handling code here:
        this.dispose();
        jfMantemientoInscripciones mantenimeintoinscripciones = new jfMantemientoInscripciones();
        mantenimeintoinscripciones.setVisible(true); 
    }//GEN-LAST:event_jmMttomantenimientoInscripcionesActionPerformed

    private void jmMttoNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMttoNotasActionPerformed
        // TODO add your handling code here:
        this.dispose();
        jfNotas notas = new jfNotas();
        notas.setVisible(true);
        
    }//GEN-LAST:event_jmMttoNotasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmConsultas;
    private javax.swing.JMenu jmMtto;
    private javax.swing.JMenuItem jmMttoEstudiantes;
    private javax.swing.JMenuItem jmMttoInscripciones;
    private javax.swing.JMenuItem jmMttoNotas;
    private javax.swing.JMenuItem jmMttoiUsuarios;
    private javax.swing.JMenuItem jmMttomantenimientoInscripciones;
    private javax.swing.JMenu jmReportes;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenuItem jmiListar;
    private javax.swing.JMenuItem jmiReporteUsuarios;
    // End of variables declaration//GEN-END:variables
}
