/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.ConexionSql;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date; 

/**
 *
 * @author ProgrammerPC
 */
public class jfNotas extends javax.swing.JFrame {

    /**
     * Creates new form jfNotas
     */
    public jfNotas() {
        initComponents();
        this.setLocationRelativeTo(null);
        tfIdInscripcion.setEditable(false); 
        
        jtIdnota1.setEditable(false); 
        jtMateria1.setEditable(false); 
        jtPromMat1.setEditable(false);

        jtIdnota2.setEditable(false); 
        jtMateria2.setEditable(false); 
        jtPromMat2.setEditable(false); 
        
        jtIdnota3.setEditable(false); 
        jtMateria3.setEditable(false); 
        jtPromMat3.setEditable(false); 
        
        jtIdnota4.setEditable(false); 
        jtMateria4.setEditable(false); 
        jtPromMat4.setEditable(false); 
        
        jtIdnota5.setEditable(false); 
        jtMateria5.setEditable(false); 
        jtPromMat5.setEditable(false); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfCarnet = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfIdInscripcion = new javax.swing.JTextField();
        btnBuscarCarnet = new javax.swing.JButton();
        btnbuscarNombre = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnbuscarApellido = new javax.swing.JButton();
        tfNombre = new javax.swing.JTextField();
        tfApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtIdnota1 = new javax.swing.JTextField();
        jtIdnota2 = new javax.swing.JTextField();
        jtIdnota3 = new javax.swing.JTextField();
        jtIdnota4 = new javax.swing.JTextField();
        jtIdnota5 = new javax.swing.JTextField();
        jtMateria1 = new javax.swing.JTextField();
        jtMateria2 = new javax.swing.JTextField();
        jtMateria3 = new javax.swing.JTextField();
        jtMateria4 = new javax.swing.JTextField();
        jtMateria5 = new javax.swing.JTextField();
        jtEv1Mat1 = new javax.swing.JTextField();
        jtEv1Mat2 = new javax.swing.JTextField();
        jtEv1Mat3 = new javax.swing.JTextField();
        jtEv1Mat4 = new javax.swing.JTextField();
        jtEv1Mat5 = new javax.swing.JTextField();
        jtEv2Mat1 = new javax.swing.JTextField();
        jtEv2Mat2 = new javax.swing.JTextField();
        jtEv2Mat3 = new javax.swing.JTextField();
        jtEv2Mat4 = new javax.swing.JTextField();
        jtEv2Mat5 = new javax.swing.JTextField();
        jtEv3Mat1 = new javax.swing.JTextField();
        jtEv3Mat2 = new javax.swing.JTextField();
        jtEv3Mat3 = new javax.swing.JTextField();
        jtEv3Mat4 = new javax.swing.JTextField();
        jtEv3Mat5 = new javax.swing.JTextField();
        jtEv4Mat1 = new javax.swing.JTextField();
        jtEv4Mat2 = new javax.swing.JTextField();
        jtEv4Mat3 = new javax.swing.JTextField();
        jtEv4Mat4 = new javax.swing.JTextField();
        jtEv4Mat5 = new javax.swing.JTextField();
        jtEv5Mat1 = new javax.swing.JTextField();
        jtEv5Mat2 = new javax.swing.JTextField();
        jtEv5Mat3 = new javax.swing.JTextField();
        jtEv5Mat4 = new javax.swing.JTextField();
        jtEv5Mat5 = new javax.swing.JTextField();
        jtPromMat1 = new javax.swing.JTextField();
        jtPromMat2 = new javax.swing.JTextField();
        jtPromMat3 = new javax.swing.JTextField();
        jtPromMat4 = new javax.swing.JTextField();
        jtPromMat5 = new javax.swing.JTextField();
        btnCerrar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 204, 0));
        jLabel1.setText("Mantenimiento de Notas");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Id Inscripcion");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Carnet:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Nombres: ");

        btnBuscarCarnet.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBuscarCarnet.setText("Buscar Carnet");
        btnBuscarCarnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCarnetActionPerformed(evt);
            }
        });

        btnbuscarNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnbuscarNombre.setText("Buscar Nombre");
        btnbuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarNombreActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Apellidos:");

        btnbuscarApellido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnbuscarApellido.setText("Buscar Apellido");
        btnbuscarApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarApellidoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Id Nota");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Materia");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Evaluacion 5");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Evaluacion 1");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Evaluacion 2");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Evaluacion 3");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Evaluacion 4");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Promedio");

        jtEv5Mat5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtEv5Mat5ActionPerformed(evt);
            }
        });

        btnCerrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAgregar.setText("Guardar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfIdInscripcion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfApellido, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCarnet, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNombre, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnbuscarApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addComponent(btnbuscarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscarCarnet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtIdnota2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtMateria2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtEv1Mat2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtEv2Mat2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtEv3Mat2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtEv4Mat2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtEv5Mat2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtPromMat2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtIdnota3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtMateria3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtEv1Mat3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtEv2Mat3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtEv3Mat3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtEv4Mat3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtEv5Mat3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtPromMat3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtIdnota1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtEv1Mat1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtEv2Mat1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtEv3Mat1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtEv4Mat1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtEv5Mat1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtPromMat1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(610, 610, 610))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jtIdnota4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtMateria4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtEv1Mat4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtEv2Mat4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtEv3Mat4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtEv4Mat4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jtIdnota5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtMateria5, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtEv1Mat5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtEv2Mat5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtEv3Mat5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtEv4Mat5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jtEv5Mat5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtPromMat5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jtEv5Mat4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtPromMat4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfIdInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscarCarnet)
                        .addGap(5, 5, 5)
                        .addComponent(btnbuscarNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbuscarApellido)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtIdnota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEv1Mat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEv2Mat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEv3Mat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEv4Mat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEv5Mat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtPromMat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtIdnota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtMateria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEv1Mat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEv2Mat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEv3Mat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEv4Mat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEv5Mat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtPromMat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtIdnota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtMateria3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEv1Mat3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEv2Mat3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEv3Mat3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEv4Mat3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEv5Mat3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtPromMat3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtIdnota4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtMateria4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEv1Mat4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEv2Mat4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEv3Mat4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEv4Mat4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEv5Mat4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtPromMat4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtIdnota5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtMateria5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEv1Mat5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEv2Mat5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEv3Mat5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEv4Mat5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEv5Mat5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtPromMat5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar)
                    .addComponent(btnAgregar))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarCarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCarnetActionPerformed
        try {
            // TODO add your handling code here:
            Connection conex = ConexionSql.getInstancia().getConexion();
            CallableStatement sql = conex.prepareCall("{call [SP_ConsultarNotasEstudiantes](?,?,?)}");
            String carnet = tfCarnet.getText();
            sql.setString(1, carnet);
            sql.setString(2, "");
            sql.setString(3, "");
            ResultSet rs = sql.executeQuery();
            if (rs.next()){ //Valida si la consulta se ejecutó con éxito
                if (rs.getInt(1) > 0){//Valida si existen los datos buscados
                    tfIdInscripcion.setText(String.valueOf(rs.getInt("IdInscripcion")));
                    tfCarnet.setText(rs.getString("Carnet"));
                    tfNombre.setText(rs.getString("Nombres"));
                    tfApellido.setText(rs.getString("Apellidos"));
                    llenarNotas(rs.getInt("IdInscripcion"));
                    
                }
                else{
                    JOptionPane.showMessageDialog(null, "El usuario no existe o no tiene ninguna matricula activa");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "La consulta no se pudo ejecutar");
            }
        } catch (Exception ex) {
            Logger.getLogger(jfEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarCarnetActionPerformed

    private void btnbuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarNombreActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection conex = ConexionSql.getInstancia().getConexion();
            CallableStatement sql = conex.prepareCall("{call [SP_ConsultarNotasEstudiantes](?,?,?)}");
            String nombre = tfNombre.getText();
            sql.setString(1, "");
            sql.setString(2, nombre);
            sql.setString(3, "");
            ResultSet rs = sql.executeQuery();
            if (rs.next()){ //Valida si la consulta se ejecutó con éxito
                if (rs.getInt(1) > 0){//Valida si existen los datos buscados
                    tfIdInscripcion.setText(String.valueOf(rs.getInt("IdInscripcion")));
                    tfCarnet.setText(rs.getString("Carnet"));
                    tfNombre.setText(rs.getString("Nombres"));
                    tfApellido.setText(rs.getString("Apellidos"));
                    llenarNotas(rs.getInt("IdInscripcion"));
                    
                }
                else{
                    JOptionPane.showMessageDialog(null, "El usuario no existe o no tiene ninguna matricula activa");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "La consulta no se pudo ejecutar");
            }
        } catch (Exception ex) {
            Logger.getLogger(jfEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnbuscarNombreActionPerformed

    private void btnbuscarApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarApellidoActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection conex = ConexionSql.getInstancia().getConexion();
            CallableStatement sql = conex.prepareCall("{call [SP_ConsultarNotasEstudiantes](?,?,?)}");
            String apellido = tfApellido.getText();
            sql.setString(1, "");
            sql.setString(2, "");
            sql.setString(3, apellido);
            ResultSet rs = sql.executeQuery();
            if (rs.next()){ //Valida si la consulta se ejecutó con éxito
                if (rs.getInt(1) > 0){//Valida si existen los datos buscados
                    tfIdInscripcion.setText(String.valueOf(rs.getInt("IdInscripcion")));
                    tfCarnet.setText(rs.getString("Carnet"));
                    tfNombre.setText(rs.getString("Nombres"));
                    tfApellido.setText(rs.getString("Apellidos"));
                    llenarNotas(rs.getInt("IdInscripcion"));
                    
                }
                else{
                    JOptionPane.showMessageDialog(null, "El usuario no existe o no tiene ninguna matricula activa");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "La consulta no se pudo ejecutar");
            }
        } catch (Exception ex) {
            Logger.getLogger(jfEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnbuscarApellidoActionPerformed
    
    private void vaciarNotas(){
        
        jtIdnota1.setText("");
        jtMateria1.setText("");
        jtEv1Mat1.setText("");
        jtEv2Mat1.setText("");
        jtEv3Mat1.setText("");
        jtEv4Mat1.setText("");
        jtEv5Mat1.setText("");
        jtPromMat1.setText("");

        jtIdnota2.setText("");
        jtMateria2.setText("");
        jtEv1Mat2.setText("");
        jtEv2Mat2.setText("");
        jtEv3Mat2.setText("");
        jtEv4Mat2.setText("");
        jtEv5Mat2.setText("");
        jtPromMat2.setText("");
        
        jtIdnota3.setText("");
        jtMateria3.setText("");
        jtEv1Mat3.setText("");
        jtEv2Mat3.setText("");
        jtEv3Mat3.setText("");
        jtEv4Mat3.setText("");
        jtEv5Mat3.setText("");
        jtPromMat3.setText("");
        
        jtIdnota4.setText("");
        jtMateria4.setText("");
        jtEv1Mat4.setText("");
        jtEv2Mat4.setText("");
        jtEv3Mat4.setText("");
        jtEv4Mat4.setText("");
        jtEv5Mat4.setText("");
        jtPromMat4.setText("");
        
        jtIdnota5.setText("");
        jtMateria5.setText("");
        jtEv1Mat5.setText("");
        jtEv2Mat5.setText("");
        jtEv3Mat5.setText("");
        jtEv4Mat5.setText("");
        jtEv5Mat5.setText("");
        jtPromMat5.setText("");
    }
    
    int i;
    private void llenarNotas(int id){
        vaciarNotas();
        try {
            
            Connection conex = ConexionSql.getInstancia().getConexion();
            
            CallableStatement sqlMateriasInscritas= conex.prepareCall("select DetalleNotas.*,NombreMateria\n" +
            "from  Estudiantes \n" +
            "inner join Inscripciones on Estudiantes.IdEstudiante = Inscripciones.IdEstudiante \n" +
            "inner join InscripcionesDetalles on InscripcionesDetalles.IdInscripcion = Inscripciones.IdInscripcion\n" +
            "inner join DetalleNotas on InscripcionesDetalles.IdInscripcionesDetalles = DetalleNotas.IdDetalleInscripcion\n" +
            "inner join Materias on Materias.IdMateria = InscripcionesDetalles.IdMateria\n" +
            "WHERE Inscripciones.estado=0 and InscripcionesDetalles.estado=0 and Inscripciones.IdInscripcion="+id);
            ResultSet rs2 = sqlMateriasInscritas.executeQuery();   
            i=1;
            while(rs2.next()){                
                if(i==1){
                    jtIdnota1.setText(String.valueOf(rs2.getInt("IdDetalleNotas")));
                    jtMateria1.setText(rs2.getString("NombreMateria"));
                    jtEv1Mat1.setText(rs2.getString("Evaluacion1"));
                    jtEv2Mat1.setText(rs2.getString("Evaluacion2"));
                    jtEv3Mat1.setText(rs2.getString("Evaluacion3"));
                    jtEv4Mat1.setText(rs2.getString("Evaluacion4"));
                    jtEv5Mat1.setText(rs2.getString("Evaluacion5"));
                    jtPromMat1.setText(String.valueOf((rs2.getFloat("Evaluacion1")+rs2.getFloat("Evaluacion2")+rs2.getFloat("Evaluacion3")+rs2.getFloat("Evaluacion4")+rs2.getFloat("Evaluacion5"))/5));
                }
                if(i==2){
                    jtIdnota2.setText(String.valueOf(rs2.getInt("IdDetalleNotas")));
                    jtMateria2.setText(rs2.getString("NombreMateria"));
                    jtEv1Mat2.setText(rs2.getString("Evaluacion1"));
                    jtEv2Mat2.setText(rs2.getString("Evaluacion2"));
                    jtEv3Mat2.setText(rs2.getString("Evaluacion3"));
                    jtEv4Mat2.setText(rs2.getString("Evaluacion4"));
                    jtEv5Mat2.setText(rs2.getString("Evaluacion5"));
                    jtPromMat2.setText(String.valueOf((rs2.getFloat("Evaluacion1")+rs2.getFloat("Evaluacion2")+rs2.getFloat("Evaluacion3")+rs2.getFloat("Evaluacion4")+rs2.getFloat("Evaluacion5"))/5));
                }
                if(i==3){
                    jtIdnota3.setText(String.valueOf(rs2.getInt("IdDetalleNotas")));
                    jtMateria3.setText(rs2.getString("NombreMateria"));
                    jtEv1Mat3.setText(rs2.getString("Evaluacion1"));
                    jtEv2Mat3.setText(rs2.getString("Evaluacion2"));
                    jtEv3Mat3.setText(rs2.getString("Evaluacion3"));
                    jtEv4Mat3.setText(rs2.getString("Evaluacion4"));
                    jtEv5Mat3.setText(rs2.getString("Evaluacion5"));
                    jtPromMat3.setText(String.valueOf((rs2.getFloat("Evaluacion1")+rs2.getFloat("Evaluacion2")+rs2.getFloat("Evaluacion3")+rs2.getFloat("Evaluacion4")+rs2.getFloat("Evaluacion5"))/5));
                }
                if(i==4){
                    jtIdnota4.setText(String.valueOf(rs2.getInt("IdDetalleNotas")));
                    jtMateria4.setText(rs2.getString("NombreMateria"));
                    jtEv1Mat4.setText(rs2.getString("Evaluacion1"));
                    jtEv2Mat4.setText(rs2.getString("Evaluacion2"));
                    jtEv3Mat4.setText(rs2.getString("Evaluacion3"));
                    jtEv4Mat4.setText(rs2.getString("Evaluacion4"));
                    jtEv5Mat4.setText(rs2.getString("Evaluacion5"));
                    jtPromMat4.setText(String.valueOf((rs2.getFloat("Evaluacion1")+rs2.getFloat("Evaluacion2")+rs2.getFloat("Evaluacion3")+rs2.getFloat("Evaluacion4")+rs2.getFloat("Evaluacion5"))/5));
                }
                if(i==5){
                    jtIdnota5.setText(String.valueOf(rs2.getInt("IdDetalleNotas")));
                    jtMateria5.setText(rs2.getString("NombreMateria"));
                    jtEv1Mat5.setText(rs2.getString("Evaluacion1"));
                    jtEv2Mat5.setText(rs2.getString("Evaluacion2"));
                    jtEv3Mat5.setText(rs2.getString("Evaluacion3"));
                    jtEv4Mat5.setText(rs2.getString("Evaluacion4"));
                    jtEv5Mat5.setText(rs2.getString("Evaluacion5"));
                    jtPromMat5.setText(String.valueOf((rs2.getFloat("Evaluacion1")+rs2.getFloat("Evaluacion2")+rs2.getFloat("Evaluacion3")+rs2.getFloat("Evaluacion4")+rs2.getFloat("Evaluacion5"))/5));
                }
                i++;
            }

        } catch (Exception ex) {
            Logger.getLogger(jfInscripcionDetalle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void jtEv5Mat5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtEv5Mat5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtEv5Mat5ActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        jfMenu menu = new jfMenu();
        menu.setVisible(true);
    }//GEN-LAST:event_btnCerrarActionPerformed
    int j=0;
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        try {
            if((tfIdInscripcion.getText().length()!=0)){
                
                Connection conex = ConexionSql.getInstancia().getConexion();
                
                if(jtIdnota1.getText().length()>0){
                    if(Float.parseFloat(jtEv1Mat1.getText())>=0 && Float.parseFloat(jtEv1Mat1.getText())<=10.0){
                        
                    }else{
                        j++;                        
                    }                    
                    if(Float.parseFloat(jtEv2Mat1.getText())>=0 && Float.parseFloat(jtEv2Mat1.getText())<=10.0){
                        
                    }else{
                        j++;                        
                    }
                    if(Float.parseFloat(jtEv3Mat1.getText())>=0 && Float.parseFloat(jtEv3Mat1.getText())<=10.0){
                        
                    }else{
                        j++;                        
                    }                    
                    if(Float.parseFloat(jtEv4Mat1.getText())>=0 && Float.parseFloat(jtEv4Mat1.getText())<=10.0){
                        
                    }else{
                        j++;                        
                    }                    
                    if(Float.parseFloat(jtEv5Mat1.getText())>=0 && Float.parseFloat(jtEv5Mat1.getText())<=10.0){
                        
                    }else{
                        j++;                        
                    }     
                }
                if(jtIdnota2.getText().length()>0){
                    if(Float.parseFloat(jtEv1Mat2.getText())>=0 && Float.parseFloat(jtEv1Mat2.getText())<=10.0){
                        
                    }else{
                        j++;                        
                    }                    
                    if(Float.parseFloat(jtEv2Mat2.getText())>=0 && Float.parseFloat(jtEv2Mat2.getText())<=10.0){
                        
                    }else{
                        j++;                        
                    }
                    if(Float.parseFloat(jtEv3Mat2.getText())>=0 && Float.parseFloat(jtEv3Mat2.getText())<=10.0){
                        
                    }else{
                        j++;                        
                    }                    
                    if(Float.parseFloat(jtEv4Mat2.getText())>=0 && Float.parseFloat(jtEv4Mat2.getText())<=10.0){
                        
                    }else{
                        j++;                        
                    }                    
                    if(Float.parseFloat(jtEv5Mat2.getText())>=0 && Float.parseFloat(jtEv5Mat2.getText())<=10.0){
                        
                    }else{
                        j++;                        
                    }     
                }
                if(jtIdnota3.getText().length()>0){
                    if(Float.parseFloat(jtEv1Mat3.getText())>=0 && Float.parseFloat(jtEv1Mat3.getText())<=10.0){
                        
                    }else{
                        j++;                        
                    }                    
                    if(Float.parseFloat(jtEv2Mat3.getText())>=0 && Float.parseFloat(jtEv2Mat3.getText())<=10.0){
                        
                    }else{
                        j++;                        
                    }
                    if(Float.parseFloat(jtEv3Mat3.getText())>=0 && Float.parseFloat(jtEv3Mat3.getText())<=10.0){
                        
                    }else{
                        j++;                        
                    }                    
                    if(Float.parseFloat(jtEv4Mat3.getText())>=0 && Float.parseFloat(jtEv4Mat3.getText())<=10.0){
                        
                    }else{
                        j++;                        
                    }                    
                    if(Float.parseFloat(jtEv5Mat3.getText())>=0 && Float.parseFloat(jtEv5Mat3.getText())<=10.0){
                        
                    }else{
                        j++;                        
                    }     
                }
                if(jtIdnota4.getText().length()>0){
                    if(Float.parseFloat(jtEv1Mat4.getText())>=0 && Float.parseFloat(jtEv1Mat4.getText())<=10.0){
                        
                    }else{
                        j++;                        
                    }                    
                    if(Float.parseFloat(jtEv2Mat4.getText())>=0 && Float.parseFloat(jtEv2Mat4.getText())<=10.0){
                        
                    }else{
                        j++;                        
                    }
                    if(Float.parseFloat(jtEv3Mat4.getText())>=0 && Float.parseFloat(jtEv3Mat4.getText())<=10.0){
                        
                    }else{
                        j++;                        
                    }                    
                    if(Float.parseFloat(jtEv4Mat4.getText())>=0 && Float.parseFloat(jtEv4Mat4.getText())<=10.0){
                        
                    }else{
                        j++;                        
                    }                    
                    if(Float.parseFloat(jtEv5Mat4.getText())>=0 && Float.parseFloat(jtEv5Mat4.getText())<=10.0){
                        
                    }else{
                        j++;                        
                    }     
                }
                if(jtIdnota5.getText().length()>0){
                    if(Float.parseFloat(jtEv1Mat5.getText())>=0 && Float.parseFloat(jtEv1Mat5.getText())<=10.0){
                        
                    }else{
                        j++;                        
                    }                    
                    if(Float.parseFloat(jtEv2Mat5.getText())>=0 && Float.parseFloat(jtEv2Mat5.getText())<=10.0){
                        
                    }else{
                        j++;                        
                    }
                    if(Float.parseFloat(jtEv3Mat5.getText())>=0 && Float.parseFloat(jtEv3Mat5.getText())<=10.0){
                        
                    }else{
                        j++;                        
                    }                    
                    if(Float.parseFloat(jtEv4Mat5.getText())>=0 && Float.parseFloat(jtEv4Mat5.getText())<=10.0){
                        
                    }else{
                        j++;                        
                    }                    
                    if(Float.parseFloat(jtEv5Mat5.getText())>=0 && Float.parseFloat(jtEv5Mat5.getText())<=10.0){
                        
                    }else{
                        j++;                        
                    }     
                }
                
                if(j>0){
                    JOptionPane.showMessageDialog(null, "Error! Las notas no se guadaron por que tiene "+j+" errores. Por favor verifique que la nota sea un numero entre cero y diez");   
                    j=0;
                }else{
                    if(jtIdnota1.getText().length()>0){
                    
                    CallableStatement sql = conex.prepareCall("{call [SP_ActualizarNotas](?,?,?,?,?,?)}");
                    sql.setInt(1, Integer.parseInt(jtIdnota1.getText()));
                    sql.setFloat(2, Float.parseFloat(jtEv1Mat1.getText()));
                    sql.setFloat(3, Float.parseFloat(jtEv2Mat1.getText()));
                    sql.setFloat(4, Float.parseFloat(jtEv3Mat1.getText()));
                    sql.setFloat(5, Float.parseFloat(jtEv4Mat1.getText()));
                    sql.setFloat(6, Float.parseFloat(jtEv5Mat1.getText()));
                    sql.execute();                    
                    }
                    if(jtIdnota2.getText().length()>0){

                        CallableStatement sql = conex.prepareCall("{call [SP_ActualizarNotas](?,?,?,?,?,?)}");
                        sql.setInt(1, Integer.parseInt(jtIdnota2.getText()));
                        sql.setFloat(2, Float.parseFloat(jtEv1Mat2.getText()));
                        sql.setFloat(3, Float.parseFloat(jtEv2Mat2.getText()));
                        sql.setFloat(4, Float.parseFloat(jtEv3Mat2.getText()));
                        sql.setFloat(5, Float.parseFloat(jtEv4Mat2.getText()));
                        sql.setFloat(6, Float.parseFloat(jtEv5Mat2.getText()));
                        sql.execute();                    
                    }
                    if(jtIdnota3.getText().length()>0){

                        CallableStatement sql = conex.prepareCall("{call [SP_ActualizarNotas](?,?,?,?,?,?)}");
                        sql.setInt(1, Integer.parseInt(jtIdnota3.getText()));
                        sql.setFloat(2, Float.parseFloat(jtEv1Mat3.getText()));
                        sql.setFloat(3, Float.parseFloat(jtEv2Mat3.getText()));
                        sql.setFloat(4, Float.parseFloat(jtEv3Mat3.getText()));
                        sql.setFloat(5, Float.parseFloat(jtEv4Mat3.getText()));
                        sql.setFloat(6, Float.parseFloat(jtEv5Mat3.getText()));
                        sql.execute();                    
                    }
                    if(jtIdnota4.getText().length()>0){

                        CallableStatement sql = conex.prepareCall("{call [SP_ActualizarNotas](?,?,?,?,?,?)}");
                        sql.setInt(1, Integer.parseInt(jtIdnota4.getText()));
                        sql.setFloat(2, Float.parseFloat(jtEv1Mat4.getText()));
                        sql.setFloat(3, Float.parseFloat(jtEv2Mat4.getText()));
                        sql.setFloat(4, Float.parseFloat(jtEv3Mat4.getText()));
                        sql.setFloat(5, Float.parseFloat(jtEv4Mat4.getText()));
                        sql.setFloat(6, Float.parseFloat(jtEv5Mat4.getText()));
                        sql.execute();                    
                    }
                    if(jtIdnota5.getText().length()>0){

                        CallableStatement sql = conex.prepareCall("{call [SP_ActualizarNotas](?,?,?,?,?,?)}");
                        sql.setInt(1, Integer.parseInt(jtIdnota5.getText()));
                        sql.setFloat(2, Float.parseFloat(jtEv1Mat5.getText()));
                        sql.setFloat(3, Float.parseFloat(jtEv2Mat5.getText()));
                        sql.setFloat(4, Float.parseFloat(jtEv3Mat5.getText()));
                        sql.setFloat(5, Float.parseFloat(jtEv4Mat5.getText()));
                        sql.setFloat(6, Float.parseFloat(jtEv5Mat5.getText()));
                        sql.execute();                    
                    }
                    JOptionPane.showMessageDialog(null, "Exito! Las notas se guadaron con exito");   
                    llenarNotas(Integer.parseInt(tfIdInscripcion.getText()));
                
                }
            }else{
                JOptionPane.showMessageDialog(null, "Haga la busqueda de un alumno!");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfNotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarCarnet;
    public javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnbuscarApellido;
    private javax.swing.JButton btnbuscarNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jtEv1Mat1;
    private javax.swing.JTextField jtEv1Mat2;
    private javax.swing.JTextField jtEv1Mat3;
    private javax.swing.JTextField jtEv1Mat4;
    private javax.swing.JTextField jtEv1Mat5;
    private javax.swing.JTextField jtEv2Mat1;
    private javax.swing.JTextField jtEv2Mat2;
    private javax.swing.JTextField jtEv2Mat3;
    private javax.swing.JTextField jtEv2Mat4;
    private javax.swing.JTextField jtEv2Mat5;
    private javax.swing.JTextField jtEv3Mat1;
    private javax.swing.JTextField jtEv3Mat2;
    private javax.swing.JTextField jtEv3Mat3;
    private javax.swing.JTextField jtEv3Mat4;
    private javax.swing.JTextField jtEv3Mat5;
    private javax.swing.JTextField jtEv4Mat1;
    private javax.swing.JTextField jtEv4Mat2;
    private javax.swing.JTextField jtEv4Mat3;
    private javax.swing.JTextField jtEv4Mat4;
    private javax.swing.JTextField jtEv4Mat5;
    private javax.swing.JTextField jtEv5Mat1;
    private javax.swing.JTextField jtEv5Mat2;
    private javax.swing.JTextField jtEv5Mat3;
    private javax.swing.JTextField jtEv5Mat4;
    private javax.swing.JTextField jtEv5Mat5;
    private javax.swing.JTextField jtIdnota1;
    private javax.swing.JTextField jtIdnota2;
    private javax.swing.JTextField jtIdnota3;
    private javax.swing.JTextField jtIdnota4;
    private javax.swing.JTextField jtIdnota5;
    private javax.swing.JTextField jtMateria1;
    private javax.swing.JTextField jtMateria2;
    private javax.swing.JTextField jtMateria3;
    private javax.swing.JTextField jtMateria4;
    private javax.swing.JTextField jtMateria5;
    private javax.swing.JTextField jtPromMat1;
    private javax.swing.JTextField jtPromMat2;
    private javax.swing.JTextField jtPromMat3;
    private javax.swing.JTextField jtPromMat4;
    private javax.swing.JTextField jtPromMat5;
    public javax.swing.JTextField tfApellido;
    public javax.swing.JTextField tfCarnet;
    public javax.swing.JTextField tfIdInscripcion;
    public javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
